name: CMake
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release



jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    env:
      # Set your boost version
      BOOST_VERSION: 1.78.0
      # Parent directory where Boost will be installed
      BOOST_INSTALL_PARENT: ${{ github.workspace }}
      # Directory that will contain the Boost installation and is cached between runs
      BOOST_CACHE_DIR: ${{ github.workspace }}/boost

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Ensure Boost cache directory
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path "${{ env.BOOST_CACHE_DIR }}" -Force | Out-Null

# Retrieve the cache, uses cache@v4
    - name: Cache boost
      uses: actions/cache@v4
      id: cache-boost
      with:
        # Set the path to cache
        path: ${{ env.BOOST_CACHE_DIR }}
        # Use the version as the key to only cache the correct version
        key: boost-${{env.BOOST_VERSION}}

    # Actual install step (only runs if the cache is empty)
    - name: Install boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      uses: MarkusJx/install-boost@v2.3.0
      with:
        # Set the boost version (required)
        boost_version: ${{env.BOOST_VERSION}}
        # Set the install directory
        boost_install_dir: ${{ env.BOOST_INSTALL_PARENT }}
        # Set your platform version
        platform_version: 2022
        # Set the toolset
        toolset: msvc

    - name: Locate Boost root
      id: locate-boost
      shell: pwsh
      run: |
        $cacheDir = "${{ env.BOOST_CACHE_DIR }}"
        if (-not (Test-Path $cacheDir)) {
          throw "Boost cache directory '$cacheDir' does not exist."
        }

        $candidates = Get-ChildItem -Path $cacheDir -Directory | Sort-Object Name
        $boostDir = $candidates | Where-Object { $_.Name -match '^boost_\d' } | Select-Object -First 1
        if ($null -eq $boostDir) {
          $boostDir = $candidates | Where-Object { $_.Name -match '^boost' } | Select-Object -First 1
        }
        if ($null -eq $boostDir -and $candidates.Count -gt 0) {
          $boostDir = $candidates[0]
        }

        if ($null -ne $boostDir) {
          $boostRoot = $boostDir.FullName
        } else {
          $boostRoot = $cacheDir
        }

        Write-Host "Using Boost root at $boostRoot"
        "boost-root=$boostRoot" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        "BOOST_ROOT=$boostRoot" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        BOOST_ROOT: ${{ steps.locate-boost.outputs.boost-root }}


    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      env:
        BOOST_ROOT: ${{ steps.locate-boost.outputs.boost-root }}
